-- Migration: 003_create_ride_forms_table.sql
-- Description: Creates ride_forms table based on the ride request form

-- Ride Forms Table
CREATE TABLE ride_forms (
    id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    program_id INT4 NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    location TEXT NOT NULL,
    destination TEXT NOT NULL,
    datetime TIMESTAMP WITH TIME ZONE NOT NULL,
    passengers INT NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- Create index on user_id for faster lookups
CREATE INDEX idx_ride_forms_user_id ON ride_forms(user_id);
-- Create index on program_id for faster lookups
CREATE INDEX idx_ride_forms_program_id ON ride_forms(program_id);