-- Migration: 004_create_support_chats_table.sql
-- Description: Creates the support_chats table for messaging functionality

-- Support Chats Table
CREATE TABLE support_chats (
    id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    program_id INT4 NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
    chat_title TEXT NOT NULL,
    messages JSONB NOT NULL DEFAULT '[]'::jsonb, -- Array of message objects with sender, message and time_sent
    device_id TEXT NOT NULL, -- References the device ID of the user
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Create an index on device_id for faster lookups
CREATE INDEX idx_support_chats_device_id ON support_chats(device_id);
-- Create index on program_id for faster lookups
CREATE INDEX idx_support_chats_program_id ON support_chats(program_id);