-- Migration: 001_create_initial_tables.sql
-- Description: Creates initial tables for the ICYPAA application.

-- Users Table
CREATE TABLE users (
    id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    device_id TEXT NOT NULL UNIQUE, -- Assuming device_id should be unique
    first_name TEXT NOT NULL,
    last_initial TEXT NOT NULL,
    profile_image TEXT,
    schedule JSONB, -- { saved_events: string[], shared_with: string[], shared_by: string[] }
    settings JSONB, -- { notifications: boolean, schedule_notifications: boolean, ... }
    -- Link to Supabase auth user. Set NULL if the auth user is deleted.
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- Programs Table
CREATE TABLE programs (
    id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    logo TEXT, -- Optional
    start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE NOT NULL,
    location JSONB NOT NULL, -- { name: string, address: { street: string, ... } }
    venue_rooms TEXT[], -- string[]
    hospitality JSONB NOT NULL, -- { location: string, times: { day: string, ... }[] }
    theme TEXT NOT NULL,
    big_book_passage TEXT NOT NULL,
    design JSONB, -- { primary_color: string, ... }
    promote NUMERIC[] -- [event_id, event_id, ...]
);

-- Event Categories Table
CREATE TABLE event_categories (
    id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    program_id INT4 NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    color TEXT NOT NULL
);
CREATE INDEX idx_event_categories_program_id ON event_categories(program_id);

-- Events Table
CREATE TABLE events (
    id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    program_id INT4 NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    image TEXT, -- Optional
    date DATE NOT NULL, -- Assuming the string maps directly to a DATE
    start_time TIME WITHOUT TIME ZONE NOT NULL, -- Assuming the string maps directly to TIME
    end_time TIME WITHOUT TIME ZONE NOT NULL, -- Assuming the string maps directly to TIME
    location TEXT NOT NULL, -- Refers to venue room name or similar
    event_category_id INT4 NOT NULL REFERENCES event_categories(id) ON DELETE CASCADE, -- Cascade delete if category is removed
    can_save BOOLEAN NOT NULL,
    speakers TEXT[] -- string[]
);
CREATE INDEX idx_events_program_id ON events(program_id);
CREATE INDEX idx_events_event_category_id ON events(event_category_id);

-- Activities Table
CREATE TABLE activities (
    id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    program_id INT4 NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
    category TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    image TEXT, -- Optional
    location TEXT NOT NULL,
    distance NUMERIC -- Using NUMERIC for potential decimal values (e.g., miles)
);
CREATE INDEX idx_activities_program_id ON activities(program_id);

-- Food Table (Based on Food type in activities.ts)
CREATE TABLE food (
    id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    program_id INT4 NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
    category TEXT NOT NULL, -- e.g., 'Restaurant', 'Cafe'
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    image TEXT, -- Optional
    location TEXT NOT NULL,
    distance NUMERIC -- Distance from venue
);
CREATE INDEX idx_food_program_id ON food(program_id);


-- Venues Table
CREATE TABLE venues (
    id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    program_id INT4 NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
    floors JSONB, -- { name: string, url: string, description: string }[]
    amenities JSONB -- { name: string, description: string }[]
);
CREATE INDEX idx_venues_program_id ON venues(program_id);

-- Transportation Table
CREATE TABLE transportation (
    id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    program_id INT4 NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
    maps JSONB, -- { name: string, url: string, description: string }[]
    travel_details JSONB -- { name: string, description: string }[]
);
CREATE INDEX idx_transportation_program_id ON transportation(program_id);

-- End of migration file