-- Migration: 002_create_accessibility_forms_table.sql
-- Description: Creates accessibility_forms table based on the accessibility request form

-- Accessibility Forms Table
CREATE TABLE accessibility_forms (
    id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    program_id INT4 NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT NOT NULL,
    need_type TEXT NOT NULL,
    details TEXT,
    arrival_date TEXT NOT NULL,
    duration TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- Create index on user_id for faster lookups
CREATE INDEX idx_accessibility_forms_user_id ON accessibility_forms(user_id);
-- Create index on program_id for faster lookups
CREATE INDEX idx_accessibility_forms_program_id ON accessibility_forms(program_id);