-- Migration: 005_create_hospitality_forms_table.sql
-- Description: Creates hospitality_forms table based on the hospitality request form

-- Hospitality Forms Table
CREATE TABLE hospitality_forms (
    id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    program_id INT4 NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
    group_name TEXT NOT NULL,
    item_description TEXT NOT NULL,
    allergies TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- Create index on user_id for faster lookups
CREATE INDEX idx_hospitality_forms_user_id ON hospitality_forms(user_id);
-- Create index on program_id for faster lookups
CREATE INDEX idx_hospitality_forms_program_id ON hospitality_forms(program_id);