-- Create sms_agreements table for storing SMS consent records
CREATE TABLE IF NOT EXISTS sms_agreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    device_id UUID NOT NULL UNIQUE,
    name TEXT NOT NULL,
    permission BOOLEAN NOT NULL DEFAULT true,
    ip_address INET,
    user_agent TEXT
);

-- Enable RLS on sms_agreements table
ALTER TABLE sms_agreements ENABLE ROW LEVEL SECURITY;

-- Create policies for sms_agreements table
-- Only authenticated users with admin role can view SMS agreements
CREATE POLICY "Admins can view SMS agreements" ON sms_agreements
    FOR SELECT USING (
        auth.role() = 'authenticated' AND EXISTS (
            SELECT 1 FROM roles
            WHERE roles.user_id = auth.uid()
            AND roles.role = 'admin'
        )
    );

-- Only authenticated users with admin role can manage SMS agreements
CREATE POLICY "Admins can manage SMS agreements" ON sms_agreements
    FOR ALL USING (
        auth.role() = 'authenticated' AND EXISTS (
            SELECT 1 FROM roles
            WHERE roles.user_id = auth.uid()
            AND roles.role = 'admin'
        )
    );

-- Allow anonymous users to insert and update their own SMS agreements
CREATE POLICY "Anonymous users can submit SMS agreements" ON sms_agreements
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Anonymous users can update their own SMS agreements" ON sms_agreements
    FOR UPDATE WITH CHECK (true);

-- Create indexes for better performance
CREATE INDEX idx_sms_agreements_device_id ON sms_agreements(device_id);
CREATE INDEX idx_sms_agreements_permission ON sms_agreements(permission);
CREATE INDEX idx_sms_agreements_created_at ON sms_agreements(created_at);

-- Add comments
COMMENT ON TABLE sms_agreements IS 'Records of user consent to receive SMS messages';
COMMENT ON COLUMN sms_agreements.device_id IS 'Unique device identifier (UUID) for tracking consent';
COMMENT ON COLUMN sms_agreements.name IS 'Full name of the person agreeing to SMS';
COMMENT ON COLUMN sms_agreements.permission IS 'Current permission state - true for opted in, false for opted out';
COMMENT ON COLUMN sms_agreements.ip_address IS 'IP address of the user when agreement was made (for legal compliance)';
COMMENT ON COLUMN sms_agreements.user_agent IS 'User agent string when agreement was made (for legal compliance)';