-- Create table for storing panel chairpeople information
CREATE TABLE IF NOT EXISTS panel_chairpeople (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Chairperson information
    name TEXT NOT NULL,
    phone TEXT,
    
    -- Panel information
    day_time TEXT NOT NULL,
    panel_name TEXT NOT NULL,
    
    -- Link to panel_notifications if matched
    panel_id BIGINT REFERENCES panel_notifications(id) ON DELETE SET NULL,
    
    -- Store raw data from import
    raw_data JSONB DEFAULT '{}'::JSONB,
    
    -- Prevent duplicate chairpeople for the same panel
    UNIQUE(name, panel_name, day_time)
);

-- Enable RLS on panel_chairpeople table
ALTER TABLE panel_chairpeople ENABLE ROW LEVEL SECURITY;

-- Create policies for panel_chairpeople table
-- Any authenticated user can view panel chairpeople
CREATE POLICY "Authenticated users can view panel chairpeople" ON panel_chairpeople
    FOR SELECT USING (auth.role() = 'authenticated');

-- Only admin and steering can manage panel chairpeople
CREATE POLICY "Admin and steering can manage panel chairpeople" ON panel_chairpeople
    FOR ALL USING (
        auth.role() = 'authenticated' AND (
            EXISTS (
                SELECT 1 FROM roles
                WHERE roles.user_id = auth.uid()
                AND roles.role IN ('admin', 'steering')
            )
        )
    );

-- Create indexes for better performance
CREATE INDEX idx_panel_chairpeople_name ON panel_chairpeople(name);
CREATE INDEX idx_panel_chairpeople_panel_name ON panel_chairpeople(panel_name);
CREATE INDEX idx_panel_chairpeople_day_time ON panel_chairpeople(day_time);
CREATE INDEX idx_panel_chairpeople_panel_id ON panel_chairpeople(panel_id);
CREATE INDEX idx_panel_chairpeople_phone ON panel_chairpeople(phone);

-- Create function to automatically link chairpeople to panels when inserted
CREATE OR REPLACE FUNCTION auto_link_chairperson_to_panel()
RETURNS TRIGGER AS $$
BEGIN
    -- Try to find a matching panel
    IF NEW.panel_id IS NULL THEN
        SELECT id INTO NEW.panel_id
        FROM panel_notifications
        WHERE LOWER(title) = LOWER(NEW.panel_name)
        AND LOWER(time_day) LIKE LOWER('%' || NEW.day_time || '%')
        LIMIT 1;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically link chairpeople to panels
CREATE TRIGGER auto_link_chairperson_trigger
    BEFORE INSERT OR UPDATE ON panel_chairpeople
    FOR EACH ROW
    EXECUTE FUNCTION auto_link_chairperson_to_panel();

-- Add comments
COMMENT ON TABLE panel_chairpeople IS 'Storage for panel chairpeople imported from Excel';
COMMENT ON COLUMN panel_chairpeople.name IS 'Chairperson name';
COMMENT ON COLUMN panel_chairpeople.phone IS 'Chairperson phone number';
COMMENT ON COLUMN panel_chairpeople.day_time IS 'Day and time from the Excel file';
COMMENT ON COLUMN panel_chairpeople.panel_name IS 'Panel name from the Excel file';
COMMENT ON COLUMN panel_chairpeople.panel_id IS 'Foreign key to panel_notifications if matched';
COMMENT ON COLUMN panel_chairpeople.raw_data IS 'Original row data from Excel import';