-- Create roles table for user permissions
CREATE TABLE IF NOT EXISTS roles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'steering', 'host', 'volunteer')),
    permissions TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, role)
);

-- Create outreach_reminders table for meeting reminders
CREATE TABLE IF NOT EXISTS outreach_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    name TEXT NOT NULL,
    details TEXT,
    frequency TEXT NOT NULL,
    reminder_buffer TEXT NOT NULL,
    people JSONB[] NOT NULL DEFAULT '{}',
    CONSTRAINT people_structure CHECK (
        ARRAY_LENGTH(people, 1) IS NULL OR (
            SELECT BOOL_AND(
                person ? 'name' AND person ? 'phone'
                AND jsonb_typeof(person->'name') = 'string'
                AND jsonb_typeof(person->'phone') = 'string'
            )
            FROM UNNEST(people) AS person
        )
    )
);

-- Enable RLS on new tables
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE outreach_reminders ENABLE ROW LEVEL SECURITY;

-- Create policies for roles table
CREATE POLICY "Users can view their own roles" ON roles
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Admins can manage all roles" ON roles
    FOR ALL USING (
        auth.role() = 'authenticated' AND EXISTS (
            SELECT 1 FROM roles
            WHERE roles.user_id = auth.uid()
            AND roles.role = 'admin'
        )
    );

-- Create policies for outreach_reminders table
CREATE POLICY "Authorized users can view outreach reminders" ON outreach_reminders
    FOR SELECT USING (
        auth.role() = 'authenticated' AND (
            EXISTS (
                SELECT 1 FROM roles
                WHERE roles.user_id = auth.uid()
                AND roles.role IN ('admin', 'steering')
            )
            OR
            EXISTS (
                SELECT 1 FROM roles
                WHERE roles.user_id = auth.uid()
                AND roles.permissions @> ARRAY['reminders:edit']
            )
        )
    );

CREATE POLICY "Authorized users can manage outreach reminders" ON outreach_reminders
    FOR ALL USING (
        auth.role() = 'authenticated' AND (
            EXISTS (
                SELECT 1 FROM roles
                WHERE roles.user_id = auth.uid()
                AND roles.role IN ('admin', 'steering')
            )
            OR
            EXISTS (
                SELECT 1 FROM roles
                WHERE roles.user_id = auth.uid()
                AND roles.permissions @> ARRAY['reminders:edit']
            )
        )
    );

-- Create indexes for better performance
CREATE INDEX idx_roles_user_id ON roles(user_id);
CREATE INDEX idx_roles_role ON roles(role);
CREATE INDEX idx_outreach_reminders_frequency ON outreach_reminders(frequency);

-- Add comments
COMMENT ON TABLE roles IS 'User roles and permissions for access control';
COMMENT ON TABLE outreach_reminders IS 'Meeting reminders with contact information for outreach';
COMMENT ON COLUMN outreach_reminders.people IS 'Array of JSONB objects containing name and phone number for each contact';
COMMENT ON COLUMN outreach_reminders.frequency IS 'The date for one-offs or the recurring day/time';
COMMENT ON COLUMN outreach_reminders.reminder_buffer IS 'When the reminder should be sent (e.g., 1h = 1 hour before, 1d = 1 day before)';