-- Create panel_notifications table for storing panel information and panelist notifications
CREATE TABLE IF NOT EXISTS panel_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Panel basic info
    time_day TEXT NOT NULL,
    room TEXT NOT NULL,
    title TEXT NOT NULL,
    topic TEXT,
    description TEXT,
    literature_reference TEXT,

    -- Panelist information
    panelist_name TEXT NOT NULL,
    panelist_contact TEXT NOT NULL, -- email or phone
    contact_type TEXT NOT NULL CHECK (contact_type IN ('email', 'phone')),

    -- Notification tracking (using timestamps instead of booleans)
    notification_sent_at TIMESTAMP WITH TIME ZONE,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    confirmation_token UUID DEFAULT uuid_generate_v4(),

    -- Metadata
    raw_data JSONB DEFAULT '{}'::JSONB,

    UNIQUE(title, time_day, room, panelist_contact)
);

-- Enable RLS on panel_notifications table
ALTER TABLE panel_notifications ENABLE ROW LEVEL SECURITY;

-- Create policies for panel_notifications table
-- Any authenticated user can view panel notifications
CREATE POLICY "Authenticated users can view panel notifications" ON panel_notifications
    FOR SELECT USING (auth.role() = 'authenticated');

-- Only admin and steering can manage panel notifications
CREATE POLICY "Admin and steering can manage panel notifications" ON panel_notifications
    FOR ALL USING (
        auth.role() = 'authenticated' AND (
            EXISTS (
                SELECT 1 FROM roles
                WHERE roles.user_id = auth.uid()
                AND roles.role IN ('admin', 'steering')
            )
        )
    );

-- Allow anonymous users to view confirmations (for confirmation page)
CREATE POLICY "Anonymous users can view confirmations" ON panel_notifications
    FOR SELECT USING (confirmation_token IS NOT NULL);

-- Allow anonymous users to update confirmation status
CREATE POLICY "Anonymous users can confirm attendance" ON panel_notifications
    FOR UPDATE USING (confirmation_token IS NOT NULL)
    WITH CHECK (confirmation_token IS NOT NULL);

-- Create indexes for better performance
CREATE INDEX idx_panel_notifications_time_day ON panel_notifications(time_day);
CREATE INDEX idx_panel_notifications_room ON panel_notifications(room);
CREATE INDEX idx_panel_notifications_title ON panel_notifications(title);
CREATE INDEX idx_panel_notifications_contact ON panel_notifications(panelist_contact);
CREATE INDEX idx_panel_notifications_token ON panel_notifications(confirmation_token);
CREATE INDEX idx_panel_notifications_sent_at ON panel_notifications(notification_sent_at);
CREATE INDEX idx_panel_notifications_confirmed_at ON panel_notifications(confirmed_at);

-- Add comments
COMMENT ON TABLE panel_notifications IS 'Panel information and panelist notification tracking combined';
COMMENT ON COLUMN panel_notifications.time_day IS 'Day and time of the panel';
COMMENT ON COLUMN panel_notifications.confirmation_token IS 'Unique token for panelist confirmation';
COMMENT ON COLUMN panel_notifications.contact_type IS 'Type of contact method used (email or phone)';
COMMENT ON COLUMN panel_notifications.notification_sent_at IS 'Timestamp when notification was sent (null means not sent)';
COMMENT ON COLUMN panel_notifications.confirmed_at IS 'Timestamp when panelist confirmed (null means not confirmed)';