-- Add columns to track Twilio message SIDs for better delivery tracking

-- Add message SID columns for tracking individual SMS messages
ALTER TABLE panel_notifications 
ADD COLUMN IF NOT EXISTS twilio_message_sid TEXT;

ALTER TABLE panel_notifications 
ADD COLUMN IF NOT EXISTS twilio_reminder_sid TEXT;

ALTER TABLE panel_notifications 
ADD COLUMN IF NOT EXISTS twilio_reminder2_sid TEXT;

-- Add indexes for message SIDs for faster webhook lookups
CREATE INDEX IF NOT EXISTS idx_panel_notifications_twilio_message_sid 
ON panel_notifications(twilio_message_sid) 
WHERE twilio_message_sid IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_panel_notifications_twilio_reminder_sid 
ON panel_notifications(twilio_reminder_sid) 
WHERE twilio_reminder_sid IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_panel_notifications_twilio_reminder2_sid 
ON panel_notifications(twilio_reminder2_sid) 
WHERE twilio_reminder2_sid IS NOT NULL;

-- Add comments
COMMENT ON COLUMN panel_notifications.twilio_message_sid IS 'Twilio message SID for initial notification SMS';
COMMENT ON COLUMN panel_notifications.twilio_reminder_sid IS 'Twilio message SID for first reminder SMS';
COMMENT ON COLUMN panel_notifications.twilio_reminder2_sid IS 'Twilio message SID for second reminder SMS';

-- Create a table to log all SMS webhook events for debugging
CREATE TABLE IF NOT EXISTS sms_delivery_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    notification_id BIGINT REFERENCES panel_notifications(id) ON DELETE CASCADE,
    message_sid TEXT NOT NULL,
    message_status TEXT NOT NULL,
    error_code TEXT,
    error_message TEXT,
    to_number TEXT,
    from_number TEXT,
    reminder_type TEXT,
    webhook_data JSONB
);

-- Create index for faster lookups
CREATE INDEX idx_sms_delivery_logs_notification_id ON sms_delivery_logs(notification_id);
CREATE INDEX idx_sms_delivery_logs_message_sid ON sms_delivery_logs(message_sid);
CREATE INDEX idx_sms_delivery_logs_created_at ON sms_delivery_logs(created_at DESC);

-- Add RLS policies
ALTER TABLE sms_delivery_logs ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to view SMS logs
CREATE POLICY "Authenticated users can view SMS logs" ON sms_delivery_logs
    FOR SELECT USING (auth.role() = 'authenticated');

-- Allow system to insert SMS logs (via service role)
CREATE POLICY "System can insert SMS logs" ON sms_delivery_logs
    FOR INSERT WITH CHECK (true);

COMMENT ON TABLE sms_delivery_logs IS 'Logs all Twilio webhook events for SMS delivery tracking and debugging';