-- Drop the existing table if it exists to recreate with new schema
DROP TABLE IF EXISTS hospitality_hours CASCADE;

-- Create table for tracking individual hospitality volunteer hours
CREATE TABLE hospitality_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Date and time (required for ordering and uniqueness)
    date_time TIMESTAMP WITH TIME ZONE NOT NULL,
    
    -- Group information (public display)
    group_hosting TEXT, -- Group name hosting this slot (can be NULL for placeholder slots)
    group_contact TEXT, -- Primary contact name
    group_confirmed BOOLEAN DEFAULT false,
    group_phone TEXT, -- Contact phone (internal use)
    group_email TEXT, -- Contact email (internal use)
    planning_to_bring TEXT, -- What they plan to bring
    
    -- Legacy/compatibility fields
    display_name TEXT GENERATED ALWAYS AS (COALESCE(group_hosting, 'Open Slot')) STORED,
    day TEXT GENERATED ALWAYS AS (to_char(date_time, 'Mon DD')) STORED,
    time_slot TEXT GENERATED ALWAYS AS (to_char(date_time, 'HH12:MI AM')) STORED,
    room TEXT,

    -- Hours tracking (only scheduled hours)
    scheduled_hours DECIMAL(4,2) DEFAULT 2.0,

    -- Status tracking
    status TEXT DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'no_show', 'cancelled')),

    -- Link to original volunteering_interest record (for internal use only)
    volunteering_interest_id BIGINT REFERENCES volunteering_interest(id) ON DELETE CASCADE,

    -- Unique constraint: only one entry per date_time + group combination
    -- Allow NULL group_hosting for placeholder slots
    UNIQUE(date_time, group_hosting)
);

-- Enable RLS on hospitality_hours table
ALTER TABLE hospitality_hours ENABLE ROW LEVEL SECURITY;

-- Create policies for hospitality_hours table
-- Anyone can view hospitality hours (public information)
CREATE POLICY "Anyone can view hospitality hours" ON hospitality_hours
    FOR SELECT USING (true);

-- Only users with volunteering:edit permission can manage hospitality hours
CREATE POLICY "Users with volunteering:edit can manage hospitality hours" ON hospitality_hours
    FOR INSERT WITH CHECK (
        auth.role() = 'authenticated' AND (
            EXISTS (
                SELECT 1 FROM roles
                WHERE roles.user_id = auth.uid()
                AND (
                    roles.role IN ('admin', 'steering') OR
                    roles.permissions::text[] @> ARRAY['volunteering:edit']
                )
            )
        )
    );

CREATE POLICY "Users with volunteering:edit can update hospitality hours" ON hospitality_hours
    FOR UPDATE USING (
        auth.role() = 'authenticated' AND (
            EXISTS (
                SELECT 1 FROM roles
                WHERE roles.user_id = auth.uid()
                AND (
                    roles.role IN ('admin', 'steering') OR
                    roles.permissions::text[] @> ARRAY['volunteering:edit']
                )
            )
        )
    );

CREATE POLICY "Users with volunteering:edit can delete hospitality hours" ON hospitality_hours
    FOR DELETE USING (
        auth.role() = 'authenticated' AND (
            EXISTS (
                SELECT 1 FROM roles
                WHERE roles.user_id = auth.uid()
                AND (
                    roles.role IN ('admin', 'steering') OR
                    roles.permissions::text[] @> ARRAY['volunteering:edit']
                )
            )
        )
    );

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_hospitality_hours_date_time ON hospitality_hours(date_time);
CREATE INDEX IF NOT EXISTS idx_hospitality_hours_group_hosting ON hospitality_hours(group_hosting);
CREATE INDEX IF NOT EXISTS idx_hospitality_hours_status ON hospitality_hours(status);
CREATE INDEX IF NOT EXISTS idx_hospitality_hours_volunteering_interest_id ON hospitality_hours(volunteering_interest_id);
CREATE INDEX IF NOT EXISTS idx_hospitality_hours_group_confirmed ON hospitality_hours(group_confirmed);

-- Function to extract display name from volunteering_interest data
CREATE OR REPLACE FUNCTION get_hospitality_display_name(vi_id BIGINT)
RETURNS TEXT AS $$
DECLARE
    v_record RECORD;
    v_display_name TEXT;
BEGIN
    -- Get the volunteering_interest record
    SELECT name, last_initial, data->>'group_name' as group_name
    INTO v_record
    FROM volunteering_interest
    WHERE id = vi_id;

    -- Use group name if available, otherwise use First L. format
    IF v_record.group_name IS NOT NULL AND v_record.group_name != '' THEN
        v_display_name := v_record.group_name;
    ELSE
        -- Extract first name and combine with last initial
        v_display_name := split_part(v_record.name, ' ', 1) || ' ' || v_record.last_initial || '.';
    END IF;

    RETURN v_display_name;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create function to auto-populate from volunteering_interest
CREATE OR REPLACE FUNCTION create_hospitality_hours_from_interest()
RETURNS TRIGGER AS $$
DECLARE
    v_group_name TEXT;
    v_date_time TIMESTAMP WITH TIME ZONE;
BEGIN
    -- Only process hospitality type entries
    IF NEW.type = 'hospitality' THEN
        -- Get the group name if available
        v_group_name := COALESCE(NEW.data->>'group_name', NEW.name || ' ' || NEW.last_initial || '.');
        
        -- Parse date and time (you may need to adjust this based on your actual data format)
        -- For now, we'll create a timestamp from day and time_slot
        v_date_time := to_timestamp(
            (NEW.data->>'day')::TEXT || ' ' || (NEW.data->>'time_slot')::TEXT || ' 2025',
            'Mon DD HH12:MI AM YYYY'
        );

        -- Insert the hospitality hours record
        INSERT INTO hospitality_hours (
            date_time,
            group_hosting,
            group_contact,
            group_email,
            group_phone,
            volunteering_interest_id,
            status,
            scheduled_hours
        ) VALUES (
            v_date_time,
            v_group_name,
            NEW.name,
            NEW.email,
            NEW.phone,
            NEW.id,
            'scheduled',
            2.0
        )
        ON CONFLICT (date_time, group_hosting) DO NOTHING;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically create hospitality_hours entry when volunteering_interest is created
CREATE TRIGGER create_hospitality_hours_trigger
    AFTER INSERT ON volunteering_interest
    FOR EACH ROW
    EXECUTE FUNCTION create_hospitality_hours_from_interest();

-- Add comments
COMMENT ON TABLE hospitality_hours IS 'Public tracking of hospitality volunteer hours with group hosting information';
COMMENT ON COLUMN hospitality_hours.date_time IS 'Date and time of the hospitality slot';
COMMENT ON COLUMN hospitality_hours.group_hosting IS 'Name of the group hosting this time slot';
COMMENT ON COLUMN hospitality_hours.group_contact IS 'Primary contact person for the group';
COMMENT ON COLUMN hospitality_hours.group_confirmed IS 'Whether the group has confirmed their slot';
COMMENT ON COLUMN hospitality_hours.group_phone IS 'Contact phone number (internal use)';
COMMENT ON COLUMN hospitality_hours.group_email IS 'Contact email address (internal use)';
COMMENT ON COLUMN hospitality_hours.planning_to_bring IS 'What the group plans to bring for hospitality';
COMMENT ON COLUMN hospitality_hours.display_name IS 'Auto-generated display name for compatibility';
COMMENT ON COLUMN hospitality_hours.scheduled_hours IS 'Scheduled hours for the shift (default 2 hours)';
COMMENT ON COLUMN hospitality_hours.volunteering_interest_id IS 'Internal link to volunteering_interest record';
COMMENT ON COLUMN hospitality_hours.status IS 'Status of the volunteer shift';