ALTER TABLE public.programs
ADD COLUMN IF NOT EXISTS timezone text;

UPDATE public.programs
SET timezone = CASE upper(coalesce(location -> 'address' ->> 'state', ''))
  WHEN 'AL' THEN 'America/Chicago'
  WHEN 'ALABAMA' THEN 'America/Chicago'
  WHEN 'AK' THEN 'America/Anchorage'
  WHEN 'ALASKA' THEN 'America/Anchorage'
  WHEN 'AZ' THEN 'America/Phoenix'
  WHEN 'ARIZONA' THEN 'America/Phoenix'
  WHEN 'AR' THEN 'America/Chicago'
  WHEN 'ARKANSAS' THEN 'America/Chicago'
  WHEN 'CA' THEN 'America/Los_Angeles'
  WHEN 'CALIFORNIA' THEN 'America/Los_Angeles'
  WHEN 'CO' THEN 'America/Denver'
  WHEN 'COLORADO' THEN 'America/Denver'
  WHEN 'CT' THEN 'America/New_York'
  WHEN 'CONNECTICUT' THEN 'America/New_York'
  WHEN 'DE' THEN 'America/New_York'
  WHEN 'DELAWARE' THEN 'America/New_York'
  WHEN 'FL' THEN 'America/New_York'
  WHEN 'FLORIDA' THEN 'America/New_York'
  WHEN 'GA' THEN 'America/New_York'
  WHEN 'GEORGIA' THEN 'America/New_York'
  WHEN 'HI' THEN 'Pacific/Honolulu'
  WHEN 'HAWAII' THEN 'Pacific/Honolulu'
  WHEN 'ID' THEN 'America/Denver'
  WHEN 'IDAHO' THEN 'America/Denver'
  WHEN 'IL' THEN 'America/Chicago'
  WHEN 'ILLINOIS' THEN 'America/Chicago'
  WHEN 'IN' THEN 'America/Indiana/Indianapolis'
  WHEN 'INDIANA' THEN 'America/Indiana/Indianapolis'
  WHEN 'IA' THEN 'America/Chicago'
  WHEN 'IOWA' THEN 'America/Chicago'
  WHEN 'KS' THEN 'America/Chicago'
  WHEN 'KANSAS' THEN 'America/Chicago'
  WHEN 'KY' THEN 'America/New_York'
  WHEN 'KENTUCKY' THEN 'America/New_York'
  WHEN 'LA' THEN 'America/Chicago'
  WHEN 'LOUISIANA' THEN 'America/Chicago'
  WHEN 'ME' THEN 'America/New_York'
  WHEN 'MAINE' THEN 'America/New_York'
  WHEN 'MD' THEN 'America/New_York'
  WHEN 'MARYLAND' THEN 'America/New_York'
  WHEN 'MA' THEN 'America/New_York'
  WHEN 'MASSACHUSETTS' THEN 'America/New_York'
  WHEN 'MI' THEN 'America/Detroit'
  WHEN 'MICHIGAN' THEN 'America/Detroit'
  WHEN 'MN' THEN 'America/Chicago'
  WHEN 'MINNESOTA' THEN 'America/Chicago'
  WHEN 'MS' THEN 'America/Chicago'
  WHEN 'MISSISSIPPI' THEN 'America/Chicago'
  WHEN 'MO' THEN 'America/Chicago'
  WHEN 'MISSOURI' THEN 'America/Chicago'
  WHEN 'MT' THEN 'America/Denver'
  WHEN 'MONTANA' THEN 'America/Denver'
  WHEN 'NE' THEN 'America/Chicago'
  WHEN 'NEBRASKA' THEN 'America/Chicago'
  WHEN 'NV' THEN 'America/Los_Angeles'
  WHEN 'NEVADA' THEN 'America/Los_Angeles'
  WHEN 'NH' THEN 'America/New_York'
  WHEN 'NEW HAMPSHIRE' THEN 'America/New_York'
  WHEN 'NJ' THEN 'America/New_York'
  WHEN 'NEW JERSEY' THEN 'America/New_York'
  WHEN 'NM' THEN 'America/Denver'
  WHEN 'NEW MEXICO' THEN 'America/Denver'
  WHEN 'NY' THEN 'America/New_York'
  WHEN 'NEW YORK' THEN 'America/New_York'
  WHEN 'NC' THEN 'America/New_York'
  WHEN 'NORTH CAROLINA' THEN 'America/New_York'
  WHEN 'ND' THEN 'America/Chicago'
  WHEN 'NORTH DAKOTA' THEN 'America/Chicago'
  WHEN 'OH' THEN 'America/New_York'
  WHEN 'OHIO' THEN 'America/New_York'
  WHEN 'OK' THEN 'America/Chicago'
  WHEN 'OKLAHOMA' THEN 'America/Chicago'
  WHEN 'OR' THEN 'America/Los_Angeles'
  WHEN 'OREGON' THEN 'America/Los_Angeles'
  WHEN 'PA' THEN 'America/New_York'
  WHEN 'PENNSYLVANIA' THEN 'America/New_York'
  WHEN 'RI' THEN 'America/New_York'
  WHEN 'RHODE ISLAND' THEN 'America/New_York'
  WHEN 'SC' THEN 'America/New_York'
  WHEN 'SOUTH CAROLINA' THEN 'America/New_York'
  WHEN 'SD' THEN 'America/Chicago'
  WHEN 'SOUTH DAKOTA' THEN 'America/Chicago'
  WHEN 'TN' THEN 'America/Chicago'
  WHEN 'TENNESSEE' THEN 'America/Chicago'
  WHEN 'TX' THEN 'America/Chicago'
  WHEN 'TEXAS' THEN 'America/Chicago'
  WHEN 'UT' THEN 'America/Denver'
  WHEN 'UTAH' THEN 'America/Denver'
  WHEN 'VT' THEN 'America/New_York'
  WHEN 'VERMONT' THEN 'America/New_York'
  WHEN 'VA' THEN 'America/New_York'
  WHEN 'VIRGINIA' THEN 'America/New_York'
  WHEN 'WA' THEN 'America/Los_Angeles'
  WHEN 'WASHINGTON' THEN 'America/Los_Angeles'
  WHEN 'WV' THEN 'America/New_York'
  WHEN 'WEST VIRGINIA' THEN 'America/New_York'
  WHEN 'WI' THEN 'America/Chicago'
  WHEN 'WISCONSIN' THEN 'America/Chicago'
  WHEN 'WY' THEN 'America/Denver'
  WHEN 'WYOMING' THEN 'America/Denver'
  WHEN 'DC' THEN 'America/New_York'
  WHEN 'DISTRICT OF COLUMBIA' THEN 'America/New_York'
  WHEN 'PR' THEN 'America/Puerto_Rico'
  WHEN 'PUERTO RICO' THEN 'America/Puerto_Rico'
  ELSE 'America/New_York'
END
WHERE timezone IS NULL OR btrim(timezone) = '';

ALTER TABLE public.programs
ALTER COLUMN timezone SET DEFAULT 'America/New_York',
ALTER COLUMN timezone SET NOT NULL;

COMMENT ON COLUMN public.programs.timezone IS
  'IANA time zone used to interpret and display conference-local dates and times.';
