-- Complete script to update hospitality_hours table to new schema
-- Run this in your Supabase SQL editor

-- Step 1: Drop the old table and its dependencies
DROP TABLE IF EXISTS hospitality_hours CASCADE;

-- Step 2: Create the new table with proper schema
CREATE TABLE hospitality_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Date and time (required for ordering and uniqueness)
    date_time TIMESTAMP WITH TIME ZONE NOT NULL,
    
    -- Group information (public display)
    group_hosting TEXT, -- Group name hosting this slot (can be NULL for placeholder slots)
    group_contact TEXT, -- Primary contact name
    group_confirmed BOOLEAN DEFAULT false,
    group_phone TEXT, -- Contact phone (internal use)
    group_email TEXT, -- Contact email (internal use)
    planning_to_bring TEXT, -- What they plan to bring
    
    -- Legacy/compatibility fields
    room TEXT,

    -- Hours tracking (only scheduled hours)
    scheduled_hours DECIMAL(4,2) DEFAULT 2.0,

    -- Status tracking
    status TEXT DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'no_show', 'cancelled')),

    -- Link to original volunteering_interest record (for internal use only)
    volunteering_interest_id BIGINT REFERENCES volunteering_interest(id) ON DELETE CASCADE,

    -- Unique constraint: only one entry per date_time + group combination
    -- Allow NULL group_hosting for placeholder slots
    UNIQUE(date_time, group_hosting)
);

-- Step 3: Enable RLS on hospitality_hours table
ALTER TABLE hospitality_hours ENABLE ROW LEVEL SECURITY;

-- Step 4: Create policies for hospitality_hours table
-- Anyone can view hospitality hours (public information)
CREATE POLICY "Anyone can view hospitality hours" ON hospitality_hours
    FOR SELECT USING (true);

-- Only users with volunteering:edit permission can manage hospitality hours
CREATE POLICY "Users with volunteering:edit can manage hospitality hours" ON hospitality_hours
    FOR INSERT WITH CHECK (
        auth.role() = 'authenticated' AND (
            EXISTS (
                SELECT 1 FROM roles
                WHERE roles.user_id = auth.uid()
                AND (
                    roles.role IN ('admin', 'steering') OR
                    roles.permissions::text[] @> ARRAY['volunteering:edit']
                )
            )
        )
    );

CREATE POLICY "Users with volunteering:edit can update hospitality hours" ON hospitality_hours
    FOR UPDATE USING (
        auth.role() = 'authenticated' AND (
            EXISTS (
                SELECT 1 FROM roles
                WHERE roles.user_id = auth.uid()
                AND (
                    roles.role IN ('admin', 'steering') OR
                    roles.permissions::text[] @> ARRAY['volunteering:edit']
                )
            )
        )
    );

CREATE POLICY "Users with volunteering:edit can delete hospitality hours" ON hospitality_hours
    FOR DELETE USING (
        auth.role() = 'authenticated' AND (
            EXISTS (
                SELECT 1 FROM roles
                WHERE roles.user_id = auth.uid()
                AND (
                    roles.role IN ('admin', 'steering') OR
                    roles.permissions::text[] @> ARRAY['volunteering:edit']
                )
            )
        )
    );

-- Step 5: Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_hospitality_hours_date_time ON hospitality_hours(date_time);
CREATE INDEX IF NOT EXISTS idx_hospitality_hours_group_hosting ON hospitality_hours(group_hosting);
CREATE INDEX IF NOT EXISTS idx_hospitality_hours_status ON hospitality_hours(status);
CREATE INDEX IF NOT EXISTS idx_hospitality_hours_volunteering_interest_id ON hospitality_hours(volunteering_interest_id);
CREATE INDEX IF NOT EXISTS idx_hospitality_hours_group_confirmed ON hospitality_hours(group_confirmed);

-- Step 6: Add comments for documentation
COMMENT ON TABLE hospitality_hours IS 'Public tracking of hospitality volunteer hours with group hosting information';
COMMENT ON COLUMN hospitality_hours.date_time IS 'Date and time of the hospitality slot';
COMMENT ON COLUMN hospitality_hours.group_hosting IS 'Name of the group hosting this time slot';
COMMENT ON COLUMN hospitality_hours.group_contact IS 'Primary contact person for the group';
COMMENT ON COLUMN hospitality_hours.group_confirmed IS 'Whether the group has confirmed their slot';
COMMENT ON COLUMN hospitality_hours.group_phone IS 'Contact phone number (internal use)';
COMMENT ON COLUMN hospitality_hours.group_email IS 'Contact email address (internal use)';
COMMENT ON COLUMN hospitality_hours.planning_to_bring IS 'What the group plans to bring for hospitality';
COMMENT ON COLUMN hospitality_hours.scheduled_hours IS 'Scheduled hours for the shift (default 2 hours)';
COMMENT ON COLUMN hospitality_hours.volunteering_interest_id IS 'Internal link to volunteering_interest record';
COMMENT ON COLUMN hospitality_hours.status IS 'Status of the volunteer shift';

-- Step 9: Verify the table was created successfully
SELECT 
    column_name, 
    data_type, 
    is_nullable
FROM information_schema.columns
WHERE table_name = 'hospitality_hours'
ORDER BY ordinal_position;