-- Reset tables if they exist
DROP TABLE IF EXISTS registrations;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS inquiries;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS reminders;
DROP TABLE IF EXISTS volunteering;
DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS volunteering_interest;

-- Create users table
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email TEXT UNIQUE NOT NULL,
    first_name TEXT,
    last_name TEXT,
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Create events table
CREATE TABLE events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL CHECK (LENGTH(title) >= 2),
    description TEXT NOT NULL CHECK (LENGTH(description) >= 10),
    date DATE NOT NULL,
    time TIME NOT NULL,
    location TEXT NOT NULL CHECK (LENGTH(location) >= 2),
    image_url TEXT NOT NULL,
    is_icypaa_event BOOLEAN DEFAULT false,
    created_by UUID REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Create registrations table
CREATE TABLE registrations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id),
    registration_number TEXT UNIQUE NOT NULL,
    submitted_by UUID REFERENCES users(id),
    submitted_on TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Create inquiries table
CREATE TABLE inquiries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    inquiry_type TEXT NOT NULL CHECK (inquiry_type IN ('registration', 'program', 'hotel', 'other')),
    message TEXT NOT NULL,
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'closed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Create the reminders table
CREATE TABLE reminders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    type TEXT UNIQUE NOT NULL,
    time TEXT NOT NULL,
    place TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Create the volunteering_interest table for both general interest and marathon meetings
CREATE TABLE volunteering_interest (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    last_initial TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('general', 'marathon')),
    data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Create the volunteering table with JSONB for the jobs structure
CREATE TABLE volunteering (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    jobs JSON NOT NULL DEFAULT '[]'::JSON,

    CONSTRAINT jobs_structure CHECK (
        JSON_TYPEOF(jobs) = 'array'
        AND (
            SELECT BOOL_AND(
                job->>'name' IS NOT NULL
                AND JSON_TYPEOF(job->'time_slots') = 'array'
                AND (
                    SELECT BOOL_AND(
                        slot->>'time' IS NOT NULL
                        AND (slot->>'max_volunteers')::INT IS NOT NULL
                        AND JSON_TYPEOF(slot->'current_volunteers') = 'array'
                    )
                    FROM JSON_ARRAY_ELEMENTS(job->'time_slots') slot
                )
            )
            FROM JSON_ARRAY_ELEMENTS(jobs) job
        )
    )
);

-- Create reports table
CREATE TABLE reports (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    team TEXT NOT NULL CHECK (team IN ('MAIN_MEETING', 'HOST_TEAM_1', 'HOST_TEAM_2', 'HOST_TEAM_3')),
    chair_position TEXT NOT NULL,
    current_work TEXT NOT NULL,
    needs_help TEXT NOT NULL,
    team_meeting_items TEXT NOT NULL,
    agenda_doc_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert sample data for testing

-- Sample users
INSERT INTO users (email, first_name, last_name, phone) VALUES
('admin@icypaa.org', 'Admin', 'User', '555-0100'),
('host@icypaa.org', 'Host', 'Committee', '555-0101'),
('volunteer@icypaa.org', 'Volunteer', 'Helper', '555-0102');

-- Sample events
INSERT INTO events (title, description, date, time, location, image_url, is_icypaa_event, created_by) VALUES
('Opening Meeting', 'Join us for the opening meeting of the 65th ICYPAA', '2024-08-01', '19:00', 'Main Ballroom', 'https://example.com/images/opening.jpg', true, (SELECT id FROM users WHERE email = 'admin@icypaa.org')),
('Speaker Meeting', 'Main Speaker Meeting featuring recovery speakers', '2024-08-02', '20:00', 'Grand Ballroom', 'https://example.com/images/speaker.jpg', true, (SELECT id FROM users WHERE email = 'host@icypaa.org')),
('Workshop', 'Young and Sober Workshop', '2024-08-02', '14:00', 'Conference Room A', 'https://example.com/images/workshop.jpg', true, (SELECT id FROM users WHERE email = 'host@icypaa.org'));

-- Sample registrations
INSERT INTO registrations (user_id, registration_number, submitted_by) VALUES
((SELECT id FROM users WHERE email = 'volunteer@icypaa.org'), 'REG001', (SELECT id FROM users WHERE email = 'admin@icypaa.org')),
((SELECT id FROM users WHERE email = 'host@icypaa.org'), 'REG002', (SELECT id FROM users WHERE email = 'admin@icypaa.org'));

-- Sample inquiries
INSERT INTO inquiries (first_name, last_name, email, phone, inquiry_type, message) VALUES
('John', 'Doe', 'john@example.com', '555-0123', 'registration', 'How do I register for the conference?'),
('Jane', 'Smith', 'jane@example.com', '555-0124', 'hotel', 'Is there a conference room rate available?'),
('Bob', 'Wilson', 'bob@example.com', '555-0125', 'program', 'What time does registration open?');

-- Add initial reminder data
INSERT INTO reminders (type, time, place, message)
VALUES
    ('MAIN_MEETING', '09:00', 'Main Hall', 'Main meeting starting at ${when} in ${where}. Please be on time!'),
    ('HOST_TEAM_1', '08:30', 'Room 1', 'Host Team 1: Your preparation meeting is at ${when} in ${where}'),
    ('HOST_TEAM_2', '08:30', 'Room 2', 'Host Team 2: Your preparation meeting is at ${when} in ${where}'),
    ('HOST_TEAM_3', '08:30', 'Room 3', 'Host Team 3: Your preparation meeting is at ${when} in ${where}')
ON CONFLICT (type)
DO UPDATE SET
    time = EXCLUDED.time,
    place = EXCLUDED.place,
    message = EXCLUDED.message,
    modified_at = TIMEZONE('utc', NOW());

-- Add example data
INSERT INTO volunteering (event_id, jobs) VALUES
(1, '[
  {
    "name": "Registration",
    "time_slots": [
      {
        "time": "Morning (8-12)",
        "max_volunteers": 2,
        "current_volunteers": []
      },
      {
        "time": "Afternoon (12-4)",
        "max_volunteers": 2,
        "current_volunteers": []
      },
      {
        "time": "Evening (4-8)",
        "max_volunteers": 2,
        "current_volunteers": []
      }
    ]
  },
  {
    "name": "Coffee Service",
    "time_slots": [
      {
        "time": "Morning (8-12)",
        "max_volunteers": 2,
        "current_volunteers": []
      },
      {
        "time": "Afternoon (12-4)",
        "max_volunteers": 2,
        "current_volunteers": []
      },
      {
        "time": "Evening (4-8)",
        "max_volunteers": 2,
        "current_volunteers": []
      }
    ]
  }
]'::JSON);

-- Add sample volunteering interest data
INSERT INTO volunteering_interest (name, last_initial, phone, email, type, data) VALUES
('John', 'D', '555-0123', 'john@example.com', 'general',
  '{
    "interests": {
      "greeter": true,
      "security": false,
      "cleanup": true,
      "setup": true,
      "host_committee": false,
      "wherever_needed": true
    },
    "time_slots": {
      "thursday_pm": true,
      "friday_am": false,
      "friday_midday": true,
      "friday_pm": true,
      "saturday_am": false,
      "saturday_midday": true,
      "saturday_pm": true,
      "sunday_am": false,
      "sunday_midday": false,
      "sunday_pm": false,
      "other": ""
    },
    "comments": "I am available for most of the conference."
  }'::JSONB
),
('Jane', 'S', '555-0124', 'jane@example.com', 'marathon',
  '{
    "bringing_script": true,
    "meeting_committee": "Sunday Night Group",
    "day": "Aug 29",
    "time_slot": "7:00 PM"
  }'::JSONB
);

-- Add some sample reports
INSERT INTO reports (user_id, team, chair_position, current_work, needs_help, team_meeting_items, agenda_doc_id, created_at)
SELECT
    auth.uid(),
    'MAIN_MEETING',
    'Event Lead',
    'Sample report content for testing purposes.',
    'Sample current work content for testing purposes.',
    'Sample needs help content for testing purposes.',
    'Sample agenda doc ID',
    NOW()
WHERE EXISTS (SELECT 1 FROM auth.users LIMIT 1);

-- Create indexes for better query performance
CREATE INDEX idx_events_date ON events(date);
CREATE INDEX idx_registrations_number ON registrations(registration_number);
CREATE INDEX idx_inquiries_status ON inquiries(status);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_volunteering_interest_type ON volunteering_interest(type);
CREATE INDEX idx_volunteering_interest_email ON volunteering_interest(email);

-- Set up Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE volunteering ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE volunteering_interest ENABLE ROW LEVEL SECURITY;

-- Create policies
-- Users can read all public data
CREATE POLICY "Users can view all events" ON events FOR SELECT USING (true);
CREATE POLICY "Users can view all inquiries" ON inquiries FOR SELECT USING (true);

-- Only authenticated users can create events
CREATE POLICY "Authenticated users can create events" ON events
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Only admins can manage registrations
CREATE POLICY "Admins can manage registrations" ON registrations
    USING (auth.role() = 'authenticated' AND EXISTS (
        SELECT 1 FROM users
        WHERE users.id = auth.uid()
        AND email LIKE '%@icypaa.org'
    ));

-- Users can create inquiries
CREATE POLICY "Anyone can create inquiries" ON inquiries
    FOR INSERT WITH CHECK (true);

-- Enable read access for authenticated users
CREATE POLICY "Enable read access for authenticated users" ON reminders FOR SELECT USING (auth.role() = 'authenticated');

-- Enable write access for authenticated users
CREATE POLICY "Enable write access for authenticated users" ON reminders FOR ALL USING (auth.role() = 'authenticated');

-- Enable full access for authenticated users on reminders
CREATE POLICY "Authenticated users can perform all actions on reminders" ON reminders
    FOR ALL USING (auth.role() = 'authenticated');

-- Enable read access for all users
CREATE POLICY "Enable read access for all users" ON volunteering FOR SELECT USING (true);

-- Enable insert/update for authenticated users
CREATE POLICY "Enable insert/update for authenticated users" ON volunteering FOR UPDATE USING (auth.role() = 'authenticated');

-- Policy to allow authenticated users to create reports
CREATE POLICY "Authenticated users can create reports" ON reports
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Policy to allow users to view their own reports
CREATE POLICY "Users can view their own reports" ON reports
    FOR SELECT USING (auth.uid() = user_id);

-- Policies for volunteering_interest
CREATE POLICY "Anyone can submit volunteering interest" ON volunteering_interest
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Authenticated users can view volunteering interest" ON volunteering_interest
    FOR SELECT USING (auth.role() = 'authenticated');
