#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
functions_dir="$repo_root/apps/functions"
generated_marker="# Generated by scripts/configure-local-env.sh. Do not commit."
force=false

if [[ "${1:-}" == "--force" ]]; then
  force=true
elif [[ -n "${1:-}" ]]; then
  echo "Usage: $0 [--force]" >&2
  exit 2
fi

if ! status_output="$(pnpm --dir "$functions_dir" exec supabase status -o env 2>/dev/null)"; then
  echo "Local Supabase is not healthy. Run 'pnpm setup:local' first." >&2
  exit 1
fi

read_status_value() {
  local name="$1"
  printf '%s\n' "$status_output" |
    sed -n "s/^${name}=\"\\(.*\\)\"$/\\1/p" |
    head -n 1
}

api_url="$(read_status_value API_URL)"
publishable_key="$(read_status_value PUBLISHABLE_KEY)"
legacy_anon_key="$(read_status_value ANON_KEY)"
anon_key="${publishable_key:-$legacy_anon_key}"

if [[ -z "$api_url" || -z "$anon_key" ]]; then
  echo "Supabase status did not return the API URL and publishable key." >&2
  exit 1
fi

mobile_api_url="${LOCAL_SUPABASE_URL:-$api_url}"
admin_api_url="${LOCAL_ADMIN_SUPABASE_URL:-$api_url}"
admin_base_url="${LOCAL_ADMIN_API_BASE_URL:-http://127.0.0.1:3000}"

write_generated_file() {
  local target="$1"
  local contents="$2"

  if [[ -f "$target" ]] &&
    ! grep -Fq "$generated_marker" "$target" &&
    [[ "$force" != true ]]; then
    echo "Refusing to replace custom file: $target" >&2
    echo "Move it aside or rerun with --force." >&2
    exit 1
  fi

  local temp_file
  temp_file="$(mktemp "${target}.tmp.XXXXXX")"
  printf '%s\n' "$contents" >"$temp_file"
  mv "$temp_file" "$target"
}

mobile_env="$generated_marker
EXPO_PUBLIC_SUPABASE_URL=$mobile_api_url
EXPO_PUBLIC_SUPABASE_ANON_KEY=$anon_key
EXPO_PUBLIC_ADMIN_API_BASE_URL=$admin_base_url"

admin_env="$generated_marker
NEXT_PUBLIC_SUPABASE_URL=$admin_api_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=$anon_key
NEXT_PUBLIC_BASE_URL=http://127.0.0.1:3000
NEXT_PUBLIC_SITE_URL=http://127.0.0.1:3000
NEXT_PUBLIC_URL=http://127.0.0.1:3000
NEXT_PUBLIC_ENABLE_LOCAL_AUTH=true"

write_generated_file "$repo_root/apps/mobile/.env.local" "$mobile_env"
write_generated_file "$repo_root/apps/admin-web/.env.local" "$admin_env"

echo "Wrote local environment files:"
echo "  apps/mobile/.env.local -> $mobile_api_url"
echo "  apps/admin-web/.env.local -> $admin_api_url"
