import AsyncStorage from "@react-native-async-storage/async-storage"
import { createClient } from "@supabase/supabase-js"
import * as Application from "expo-application"
import { Platform } from "react-native"

const DEVICE_ID_KEY = "device_id"
const MIGRATION_COMPLETED_KEY = "device_id_migration_completed"

// We need to import the supabase config
const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL!
const supabaseAnonKey = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY!

/**
 * Checks if a device ID is a UUID (generated by the old system)
 */
const isUUID = (deviceId: string): boolean => {
  const uuidV4Regex =
    /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
  return uuidV4Regex.test(deviceId)
}

/**
 * Gets the platform-specific device identifier
 * - iOS: Uses IDFV (Identifier for Vendor)
 * - Android: Uses Android ID
 */
const getPlatformDeviceId = async (): Promise<string | null> => {
  try {
    if (Platform.OS === "ios") {
      const idfv = await Application.getIosIdForVendorAsync()
      // console.log('Got iOS IDFV:', idfv?.substring(0, 8) + '...');
      return idfv
    }

    if (Platform.OS === "android") {
      const androidId = Application.getAndroidId()
      // console.log('Got Android ID:', androidId?.substring(0, 8) + '...');
      return androidId
    }

    return null
  } catch (error) {
    console.error("Error getting platform device ID:", error)
    return null
  }
}

/**
 * Migrates a user from UUID to platform-specific device ID
 */
const migrateDeviceId = async (
  oldDeviceId: string,
  newDeviceId: string
): Promise<boolean> => {
  try {
    console.log("Migrating device ID from UUID to platform ID...")

    // Create a supabase client with the old device ID in headers
    const supabase = createClient(supabaseUrl, supabaseAnonKey, {
      global: {
        headers: {
          "X-Device-ID": oldDeviceId
        }
      }
    })

    // Check if user exists with the old device ID
    const { data: existingUser, error: fetchError } = await supabase
      .from("users")
      .select("id, device_id")
      .eq("device_id", oldDeviceId)
      .single()

    if (fetchError || !existingUser) {
      console.log("No user found with old UUID device ID, safe to switch")
      return true
    }

    console.log("Found user with UUID device ID, updating to platform ID...")

    // Update the user's device_id in the database
    const { error: updateError } = await supabase
      .from("users")
      .update({ device_id: newDeviceId })
      .eq("id", existingUser.id)

    if (updateError) {
      console.error("Error updating device ID in database:", updateError)
      return false
    }

    console.log("Successfully migrated device ID in database")
    return true
  } catch (error) {
    console.error("Error during device ID migration:", error)
    return false
  }
}

/**
 * Gets the device ID from platform-specific APIs or storage
 * Handles migration from UUID to platform-specific IDs
 */
export const getOrCreateDeviceId = async (): Promise<string> => {
  try {
    // Check what's currently in storage
    const storedId = await AsyncStorage.getItem(DEVICE_ID_KEY)
    const migrationCompleted = await AsyncStorage.getItem(
      MIGRATION_COMPLETED_KEY
    )

    // Get the platform-specific device ID
    const platformId = await getPlatformDeviceId()

    if (!platformId) {
      // No platform ID available (shouldn't happen on real devices)
      if (storedId) {
        console.log(
          "No platform ID available, using stored ID:",
          storedId.substring(0, 8) + "..."
        )
        return storedId
      }
      console.warn(
        "No platform device ID available, this should not happen in production"
      )
      throw new Error("Unable to get device ID")
    }

    // If we have a stored UUID and haven't migrated yet
    if (storedId && isUUID(storedId) && !migrationCompleted) {
      console.log("Found UUID in storage, migrating to platform ID...")

      // Attempt to migrate the user's device ID in Supabase
      const migrationSuccess = await migrateDeviceId(storedId, platformId)

      if (migrationSuccess) {
        // Update local storage with the new platform ID
        await AsyncStorage.setItem(DEVICE_ID_KEY, platformId)
        await AsyncStorage.setItem(MIGRATION_COMPLETED_KEY, "true")
        console.log("Migration completed successfully")
        return platformId
      } else {
        console.error("Migration failed, continuing with UUID for now")
        return storedId
      }
    }

    // Normal flow - use platform ID
    await AsyncStorage.setItem(DEVICE_ID_KEY, platformId)
    if (!migrationCompleted) {
      await AsyncStorage.setItem(MIGRATION_COMPLETED_KEY, "true")
    }
    return platformId
  } catch (error) {
    console.error("Error managing device ID:", error)

    // Try to use stored ID as fallback
    const storedId = await AsyncStorage.getItem(DEVICE_ID_KEY)
    if (storedId) {
      return storedId
    }

    // Last resort fallback - should never be used in production
    const fallbackId = `fallback-${Date.now()}-${Math.random()
      .toString(36)
      .substring(2, 15)}`
    await AsyncStorage.setItem(DEVICE_ID_KEY, fallbackId)
    console.warn("Using fallback device ID - this should be investigated")
    return fallbackId
  }
}

/**
 * Clears the device ID (useful for testing or account reset)
 */
export const clearDeviceId = async (): Promise<void> => {
  try {
    await AsyncStorage.removeItem(DEVICE_ID_KEY)
    await AsyncStorage.removeItem(MIGRATION_COMPLETED_KEY)
    console.log("Device ID and migration flag cleared")
  } catch (error) {
    console.error("Error clearing device ID:", error)
  }
}

/**
 * Force reset migration (useful for testing migration flow)
 */
export const resetMigration = async (): Promise<void> => {
  try {
    await AsyncStorage.removeItem(MIGRATION_COMPLETED_KEY)
    console.log("Migration flag reset - will attempt migration on next run")
  } catch (error) {
    console.error("Error resetting migration flag:", error)
  }
}

/**
 * Validates a device ID format
 */
export const isValidDeviceId = (deviceId: string): boolean => {
  // iOS IDFV format: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX (uppercase)
  const iosIdRegex =
    /^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$/

  // Android ID format: 16 character hex string (lowercase)
  const androidIdRegex = /^[0-9a-f]{16}$/

  // UUID v4 format (for backwards compatibility checking)
  const uuidV4Regex =
    /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

  // Check for valid formats
  return (
    iosIdRegex.test(deviceId) ||
    androidIdRegex.test(deviceId) ||
    uuidV4Regex.test(deviceId) ||
    deviceId.startsWith("fallback-")
  )
}
