/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/maps` | `/maps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/program` | `/program`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services/accessibility` | `/services/accessibility`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services/hospitality` | `/services/hospitality`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services/host` | `/services/host`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services` | `/services`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services/ride` | `/services/ride`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services/support` | `/services/support`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services/volunteer` | `/services/volunteer`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/services/[id]` | `/services/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/maps` | `/maps`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/program` | `/program`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/services/accessibility` | `/services/accessibility`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/services/hospitality` | `/services/hospitality`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/services/host` | `/services/host`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/services` | `/services`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/services/ride` | `/services/ride`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/services/support` | `/services/support`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/services/volunteer` | `/services/volunteer`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(tabs)'}/services/[id]` | `/services/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/notifications${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/maps${`?${string}` | `#${string}` | ''}` | `/maps${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/program${`?${string}` | `#${string}` | ''}` | `/program${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/services/accessibility${`?${string}` | `#${string}` | ''}` | `/services/accessibility${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/services/hospitality${`?${string}` | `#${string}` | ''}` | `/services/hospitality${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/services/host${`?${string}` | `#${string}` | ''}` | `/services/host${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/services${`?${string}` | `#${string}` | ''}` | `/services${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/services/ride${`?${string}` | `#${string}` | ''}` | `/services/ride${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/services/support${`?${string}` | `#${string}` | ''}` | `/services/support${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/services/volunteer${`?${string}` | `#${string}` | ''}` | `/services/volunteer${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/maps` | `/maps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/program` | `/program`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services/accessibility` | `/services/accessibility`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services/hospitality` | `/services/hospitality`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services/host` | `/services/host`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services` | `/services`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services/ride` | `/services/ride`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services/support` | `/services/support`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services/volunteer` | `/services/volunteer`; params?: Router.UnknownInputParams; } | `/+not-found` | `${'/(tabs)'}/services/${Router.SingleRoutePart<T>}` | `/services/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/services/[id]` | `/services/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
